TODO/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('todo_list.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('sign_up/', views.sign_up, name="sign_up"),
    path('superuser_signup/', views.superuser_signup, name="superuser_signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('activate/<uidb64>/<token>', views.activate, name="activate"),
    path('forgot_password/', views.forgot_password, name="forgot_password"),
    path('reset_password/', views.reset_password, name="reset_password"),
    path('activate_reset_password/<uidb64>/<token>/', views.activate_reset_password, name="activate_reset_password"),
    path('my_profile', views.my_profile, name="my_profile"),
]

todo_list/urls.py
# -*- coding: utf-8 -*-
"""
Created on Sat Dec 24 19:24:51 2022

@author: mrdag
"""

from django.urls import path
from . import views

app_name = 'todo_list'

urlpatterns = [
       path('', views.index, name="index"),
       path('schedule/<slug:slug>', views.todo_list, name="todo_list"),
       path('create_event/<slug:slug>', views.create_event, name="create_event"),
       path('edit_event/<int:id>', views.edit_events, name="edit_event"),
       path('details/<int:id>', views.details_page, name="details"),
       path('delete/<int:id>', views.delete_events, name="delete_event"),
       path('next_month/<slug:slug>', views.next_month, name="next_month"),
       path('prev_month/<slug:slug>', views.prev_month, name="prev_month"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
# Create your models here.
class AccountManager(BaseUserManager):
# To create a normal user account
       def create_user(self, email, profile_pic, passowrd=None):
# if eamil is None then raise value error
              if email is None:
                     raise ValueError('Email isnot provided')
# else create a model object and assign it to user object
              user = self.model(
                     email          = self.normalize_email(email),
                     username       = email.split('@')[0],
                     profile_pic    = profile_pic,
              )
# set password using set_password method
              user.set_password(passowrd)
# save the information by committing it to database
              user.save(using = self._db)
# return the user object
              return user
# To create a superuse account
       def create_superuser(self, email, profile_pic, password=None):
# create a user object which is manifested by the return of create_user method
              user = self.create_user(email, profile_pic , password)
# then we will conver the account to superuser by setting the following fields to True
              user.is_admin        = True
              user.is_active       = True
              user.is_staff        = True
              user.is_superadmin   = True
# Now save the configured fields in the user object
              user.save(using = self._db)
              return user
class UserAccount(AbstractBaseUser):
# set the basic fields for this account
       username     = models.CharField(max_length=50, unique=True)
       email         = models.EmailField(max_length=50, unique=True)
       profile_pic  = models.ImageField(blank=True, upload_to='userprofile/')
# fields to be filled by django
       date_created   = models.DateTimeField(auto_now=True)
       profile_updated = models.DateTimeField(auto_now=True)
       last_login     = models.DateTimeField(auto_now=True)
# fields to creae a superuse and to activate the account
       is_active     = models.BooleanField(default=False)
       is_staff      = models.BooleanField(default=False)
       is_superadmin = models.BooleanField(default=False)
       is_admin      = models.BooleanField(default=False)
# to set the emai to be used as the username
       USERNAME_FIELD = 'email'
# fields required to be filled
       #REQUIRED_FIELD = ['email']
# createing AccountManager object
       objects = AccountManager()
# own methods
       def __str__(self):
              return self.email

       def has_perm(self, perm, obj = None):
              return self.is_admin

       def has_module_perms(self, add_label):
              return True
         
    

accounts/forms.py
# -*- coding: utf-8 -*-
"""
Created on Sat Dec 24 11:04:10 2022

@author: mrdag
"""
from django import forms
from . import models

class SignUpForm(forms.ModelForm):
# create a password field and assign attributes to this field
       password = forms.CharField(widget=forms.PasswordInput(attrs={
              'class': 'field_class form-control',
              'placeholder': 'Enter your password',
       }))
       confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
              'class': 'field_class form-control',
              'placeholder': 'Confirm your password',
       }))
       class Meta():
              model = models.UserAccount
              fields = ['email', 'profile_pic', 'password']

# To validat the data the following clean method is created
       def clean(self):
              cleaned_data = super(SignUpForm, self).clean()
              password = cleaned_data.get('password')
              confirm_password = cleaned_data.get('confirm_password')

              if password != confirm_password:
                     raise forms.ValidationError("Password doesn't match")

# with this init function we initialize the SignUpForm and assign class to the fields
       def __init__(self, *args, **kwargs):
              super(SignUpForm, self).__init__(*args, **kwargs)

              for field in self.fields:
                     self.fields[field].widget.attrs['class'] = 'field_class form-control'
              self.fields['email'].widget.attrs['placeholder'] = 'Email Address'

accounts/views.py
from django.shortcuts import render, redirect
from . import forms
from .models import UserAccount
from todo_list import models
# To authenticate the login information
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# activation link packages
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
# email message packages
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
# datetime module
import datetime
# Create your views here.
def sign_up(request):
    if request.method == 'POST':
# create a form object
              form = forms.SignUpForm(request.POST)
# validate the information in the form
              if form.is_valid():
                     email = form.cleaned_data['email']
                     profile_picture = None
                     if len(request.FILES) != 0:
                            profile_picture = request.FILES['profile_img']
                     password = form.cleaned_data['password']
# # create a user account
#                    if profile_picture is None:
#                          profile_picture = "static/svg/user-solid.svg"
                     user = UserAccount.objects.create_user(
                            email, profile_picture, password
                     )
                     # form = forms.SignUpForm()
#Prepare the verificaton email
                     verification_content = {
                            'domain': get_current_site(request),
                            'user': request.user,
                            'token': default_token_generator.make_token(user),
                            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                     }
# the body part o the email
                     message = render_to_string('accounts/account_verification.html', verification_content)
# subject part of the email
                     subject = "activation link for TODO app"
# the destination email or user email address
                     to_email = email
# Compose the verification email
                     compose_email = EmailMessage(subject, message, to = [to_email])
# send the verification email
                     compose_email.send()

                     return redirect('/accounts/login/?command=verification&email='+to_email)        
    else:
        form = forms.SignUpForm()
    context = {
           'form_password': form['password'],
           'form_confirm' : form['confirm_password'],
           'form': form,
    }
    return render(request, 'accounts/sign_up.html', context=context)
# Activate the newly created account
def activate(request, uidb64, token):
# decode uid
       try:
              uid = urlsafe_base64_decode(uidb64).decode()
              user = UserAccount._default_manager.get(pk=uid)
       except(TypeError, ValueError, OverflowError, UserAccount.DoesNotExist):
              user = None
# decode  the token
       if user is not None and default_token_generator.check_token(user, token):
              user.is_active = True # activate the user account
              user.save()           # save the change
              messages.success(request, 'Congratulations! Your account is activated.')
              return redirect('accounts:login')
       else:
              messages.error(request, 'Activation link has expired')
              return redirect('accounts:sign_up')
#############################################################################################
# Login Page
def login(request):
       if request.method == 'POST':
# fetch the email address and password from the page
              email = request.POST.get('email')
              password = request.POST.get('password')
# authenticate the user using Django auth class
              user = auth.authenticate(email=email, password=password)
              if user is not None:
                     auth.login(request, user) # permit to login
                     messages.success(request, 'You are logged in') # prompt message conveying the success 
                     # url = request.META.get('HTTP_REFERER')
                     return redirect('todo_list:index')
              else:
                     messages.error(request, 'Invalid login credentials')
       return render(request, 'accounts/login.html')
############################################################################################
# Superuse Signup
def superuser_signup(request):
       if request.method == 'POST':
# create a form object
              form = forms.SignUpForm(request.POST)
# validate the information in the form
              if form.is_valid():
                     email = form.cleaned_data['email']
                     if len(request.FILES) != 0:
                            profile_picture = request.FILES['profile_img']
                     password = form.cleaned_data['password']
# create a user account
                     user = UserAccount.objects.create_superuser(
                            email, profile_picture, password
                     )
                     form = forms.SignUpForm()
       else:
              form = forms.SignUpForm()
       context = {
              'form_password': form['password'],
              'form_confirm' : form['confirm_password'],
              'form': form,
       }
       return render(request, 'accounts/superuser_signup.html', context=context)
#################################################################################################
# To logout from the current account
@login_required(login_url='accounts:login')
def logout(request):
       auth.logout(request)
       messages.success(request, 'You are logged out')
       return redirect('accounts:login')
#################################################################################################
# Forgot Password page
def forgot_password(request):
       if request.method == 'POST':
# get email address
              email = request.POST.get('email')
# check if the email exists in our database
              if UserAccount.objects.filter(email=email).exists():
# if exists then get the owner of the email
                     user = UserAccount.objects.get(email__exact=email)
# send password reset link to the email
                     password_verification = {
                            'domain': get_current_site(request),
                            'user': user,
                            'token': default_token_generator.make_token(user),
                            'uid': urlsafe_base64_encode(force_bytes(user.id)),
                     }
                     print('password_verification[uid]: ', password_verification['uid'])
# prepare the body part of the email
                     email_body = render_to_string('accounts/reset_password_verification.html', password_verification)
# prepare the subject part of the email
                     subject = 'Password reset link for calendar app'
# user email address
                     to_email = email
# compose the email
                     compose_email = EmailMessage(subject, email_body, to=[to_email])
# send the email
                     compose_email.send()
                     return redirect('accounts:forgot_password')
              else:
                     messages.error(request, 'Email address doesnot exist in our database')
                     return redirect('accounts:forgot_password')
       return render(request, 'accounts/forgot_password.html')
# Notifying the user that the password resetting link has been sent
# def password_link_sent(request):

#        return render(request, 'accounts/after_forgot_password.html')
#################################################################################################
# decodes the Reset password link sent to our email
def activate_reset_password(request, uidb64, token):
# decode the uidb64 and get the user
       try:
              uid = urlsafe_base64_decode(uidb64).decode() # decodes the uidb64 & extract uid
              print('uid: ', uid)
# from the uid get the user object
              user = UserAccount.objects.get(id = uid)
       except (TypeError, ValueError, OverflowError, UserAccount.DoesNotExist):
              user = None
# decode the token
       if user is not None and default_token_generator.check_token(user, token):
# save the uid in the session and redirect the page to reset_password
              request.session['uid'] = uid
              messages.success(request, 'Please reset your password')
              return redirect('accounts:reset_password')
       else:
              messages.error(request, 'The link has been expired, please request a new one')
              return redirect('accounts:forgot_password')
#################################################################################################
# Reset the password
def reset_password(request):
       if request.method == 'POST':
# get password from reset page
              password_1 = request.POST.get('password')
              password_2 = request.POST.get('confirm_password')
# set the new password to the user
              if password_1 == password_2:
# get the user object from session
                     uid  = request.session.get('uid')
# get the user from its id
                     user = UserAccount.objects.get(pk = uid)
# set the new password and save the changes
                     user.set_password(password_1)
                     user.save()
                     messages.success(request,'The new password has been saved')
                     return redirect('accounts:login')
              else:
                     messages.error(request, 'Passwords do not match, Please retype again')

templates/accounts/account_verification.html
{% autoescape off %}
    Hi {{ user.email }}
    Please click on the below link to confirm your registration.
    http://{{domain}}{% url 'accounts:activate' uidb64=uid token=token %}
    If you think it isnot you then please ignore this email.
{% endautoescape %}

templates/accounts/forgot_password.html
{% extends 'base.html' %}
{% block content %}
<section class="section-content padding-y">
    <div class="sign_up_container card mx-auto" style="max-width:620px; margin-top: 80px;">
        <article class="card-body">
            <header class="mb-4">
                <h4 class="card-title">Enter Your Email Address</h4>
            </header>
            <form action="{% url 'accounts:forgot_password' %}" method='POST'>
                {% csrf_token %}
                <div class="form-row">
                    <div class="col form-group">
                        <label>Email Address:</label>
                        <input type="text" class="field_class form-control" name="email" placeholder="Enter Your Email" style="max-width:300px;">
                    </div>
                </div>
                <br />
                <br />
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block" style="max-width:300px;">Sign In</button>
                </div>
            </form>
        </article>
    </div>
</section>
{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<section class="section-content padding-y">
    <div class="container sign_up_container card mx-auto" style="max-width:620px; margin-top: 80px;">
        <article class="card-body">
            <header class="mb-4">
                <h4 class="card-title">Sign In</h4>
            </header>
            <form action="{% url 'accounts:login' %}" method='POST'>
                {% csrf_token %}
                <div class="form-row">
                    <div class="col form-group">
                        <label>User Name:</label>
                        <input type="text" class="field_class form-control" name="email" placeholder="Enter Your Email" style="max-width:300px;">
                    </div>
                </div>
                <div class="form-row">
                    <div class="col form-group">
                        <label>Password:</label>
                        <input type="password" class="field_class form-control" name="password" size="10" maxlength="20" style="max-width:300px;">
                    </div>
                </div>
                <div class="form-row">
                    <a href="{% url 'accounts:sign_up' %}">
                        Sign Up if you don't have an account yet
                    </a>

                </div>
                <div class="form-row">
                    <a href="{% url 'accounts:forgot_password' %}">Forgot your password</a>

                </div>
                <br />
                <br />
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block" style="max-width:300px;">Sign In</button>
                </div>
            </form>
        </article>
    </div>
</section>
{% endblock %}

templates/accounts/my_profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

        <div class="container my_profile_container">
              <div class="profile">
                     <div class="profile-image">
                            {% if user.profile_pic %}
                                   <img src={{ user.profile_pic.url }} alt="" 
                                          style="max-width:150px; max-height:150px">
                            {% else %}
                                   <img src="{% static 'svg/user-solid.svg' %}" alt="" 
                                          style="max-width:150px; max-height:150px">
                            {% endif %}              
                     </div>
              </div>
              <div class="stats">
                     <div>
                            <h1>{{ user.username }}</h1>
                            <ul class="unorder_list">
                                   <li class="completed">{{ status.completed }}&nbsp; Completed</li>
                                   <li class="on-going">{{ status.goingon }}&nbsp; On going</li>
                                   <li class="up-coming">{{ status.upcoming }}&nbsp; Upcoming</li>
                            </ul>
                     </div>
                     <div class="stat-summary">
                           <p>Total of <strong>&nbsp;{{ status.total_schedules }}</strong> schedules.</p>

                     </div>
                     <form action="{% url 'accounts:my_profile' %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="profile_edit">
                                   <input  type="file" name="edit_profile" />
                                   <button type="submit" class="btn_submit">Change profile picture</button>
                            </div>
                     </form>
                     <div class="to_calendar">
                            <a href="{% url 'todo_list:index' %}" class="btn_submit btn_calendar">To calendar</a>

                     </div>
              </div>
        </div>
{% endblock %}

templates/accounts/reset_password.html
{% extends 'base.html' %}
{% block content %}
<section class="section-content padding-y">
    <div class="container sign_up_container card mx-auto" style="max-width:620px; margin-top: 80px;">
        <article class="card-body">
            <header class="mb-4">
                <h4 class="card-title">Reset Password</h4>
            </header>
            <form action="{% url 'accounts:reset_password' %}" method='POST'>
                {% csrf_token %}
                <div class="form-row">
                    <div class="col form-group">
                        <label>Password:</label>
                        <input type="password" class="field_class form-control" name="password" placeholder="Enter new Password" style="max-width:300px;">
                    </div>
                </div>
                <div class="form-row">
                    <div class="col form-group">
                        <label>Confirm Password:</label>
                        <input type="password" class="field_class form-control" name="confirm_password" placeholder="Confirm the password" size="10" maxlength="20" style="max-width:300px;">
                    </div>
                </div>
                <br />
                <br />
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block" style="max-width:300px;">
                        Reset
                    </button>
                </div>
            </form>
        </article>
    </div>
</section>
{% endblock %}

templates/accounts/reset_password_verification.html
{% autoescape off %}
    Hi {{ user.email }}
    Please click on the below link to confirm your registration.
    http://{{domain}}{% url 'accounts:activate_reset_password' uidb64=uid token=token %}
    If you think it isnot you then please ignore this email.
{% endautoescape %}

templates/accounts/sign_up.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="section-content padding-y">
    <div class="container sign_up_container card mx-auto" style="max-width:620px; margin-top: 80px;">
        <article class="card-body">
            <header class="mb-4">
                <h4 class="card-title">Sign Up</h4>
            </header>
            <form action="{% url 'accounts:sign_up' %}" method='POST' enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col form-group">
                        <label>Email:</label>
                        {{ form.email }}
                        {% comment %} <input type="email" class="field_class form-control" placeholder=""> {% endcomment %}
                    </div>
                </div> <!-- form-group end.// -->
                <div class="form-row">
                    <div class="col form-group">
                        {{ form_password }}
                    </div>
                    <div class="col form-group">
                        {{ form_confirm }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col form-group">
                        <label>Upload profile picture: </label>
                        <input class="field_class form-control" type="file" name="profile_img" />
                    </div>
                </div>
                {% comment %} {{ form.as_p }} {% endcomment %}
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Register</button>
                </div>
                <small class="form-text text-muted">We'll never share your email with anyone else.</small>

            </form>
        </article>
    </div>
</section>

{% endblock %}

templates/accounts/superuser_signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="section-content padding-y">
    <div class="container sign_up_container card mx-auto" style="max-width:620px; margin-top: 80px;">
        <article class="card-body">
            <header class="mb-4">
                <h4 class="card-title">Sign Up</h4>
            </header>
            <form action="{% url 'accounts:sign_up' %}" method='POST' enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col form-group">
                        <label>Email:</label>
                        {{ form.email }}
                        {% comment %} <input type="email" class="field_class form-control" placeholder=""> {% endcomment %}
                    </div>
                </div> <!-- form-group end.// -->
                <div class="form-row">
                    <div class="col form-group">
                        {{ form_password }}
                    </div>
                    <div class="col form-group">
                        {{ form_confirm }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col form-group">
                        <label>Upload profile picture: </label>
                        <input class="field_class form-control" type="file" name="profile_img" />
                    </div>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Register</button>
                </div>
                <small class="form-text text-muted">We'll never share your email with anyone else.</small>

            </form>
        </article>
    </div>
</section>

{% endblock %}