TODO/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('todo_list.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('sign_up/', views.sign_up, name="sign_up"),
    path('superuser_signup/', views.superuser_signup, name="superuser_signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('activate/<uidb64>/<token>', views.activate, name="activate"),
    path('forgot_password/', views.forgot_password, name="forgot_password"),
    path('reset_password/', views.reset_password, name="reset_password"),
    path('activate_reset_password/<uidb64>/<token>/', views.activate_reset_password, name="activate_reset_password"),
    path('my_profile', views.my_profile, name="my_profile"),
]

todo_list/urls.py
# -*- coding: utf-8 -*-
"""
Created on Sat Dec 24 19:24:51 2022

@author: mrdag
"""

from django.urls import path
from . import views

app_name = 'todo_list'

urlpatterns = [
       path('', views.index, name="index"),
       path('schedule/<slug:slug>', views.todo_list, name="todo_list"),
       path('create_event/<slug:slug>', views.create_event, name="create_event"),
       path('edit_event/<int:id>', views.edit_events, name="edit_event"),
       path('details/<int:id>', views.details_page, name="details"),
       path('delete/<int:id>', views.delete_events, name="delete_event"),
       path('next_month/<slug:slug>', views.next_month, name="next_month"),
       path('prev_month/<slug:slug>', views.prev_month, name="prev_month"),
]

todo_list/models.py
from django.db import models
from accounts.models import  UserAccount
from django.urls import reverse
from ckeditor.fields import RichTextField
# Create your models here.
class Calendar(models.Model):
       day           = models.IntegerField(null=False, default=1)
       month         = models.IntegerField(null=False, default=1)
       year          = models.IntegerField(null=False, default=2022)
       week_day      = models.IntegerField(null=False, default=1)
       slug          = models.SlugField(max_length=25, unique=True, null=True)

       def __str__(self):
              return self.slug
       def get_url(self):
              return reverse('todo_list:todo_list', args=[self.slug])

class Events(models.Model):
       event_created_at            = models.DateField(auto_now_add = True)
       event_scheduled_to_begin    = models.TimeField(auto_now=False)
       event_scheduled_to_end      = models.TimeField(auto_now=False)
       event_description           = RichTextField(blank=True, null=True)
       event_title                 = models.CharField(max_length=50)
       calendar                    = models.ForeignKey(Calendar, on_delete=models.CASCADE)
       user                        = models.ForeignKey(UserAccount, on_delete=models.CASCADE, default=None)
       def __str__(self):
              return self.event_title 

todo_list/forms.py
# -*- coding: utf-8 -*-
"""
Created on Sat Dec 24 19:21:45 2022

@author: mrdag
"""
from . import models
from django import forms

class CreateEventForm(forms.ModelForm):

       class Meta():
              model = models.Events
              fields = ('event_title', 'event_description',)

       def __init__(self, *args, **kwargs):
              super(CreateEventForm, self).__init__(*args, **kwargs)
              self.fields['event_title'].widget.attrs['class'] = 'input_field'
              self.fields['event_title'].widget.attrs['placeholder'] = 'Title'

              self.fields['event_description'].widget.attrs['class'] = 'input_field'
              self.fields['event_description'].widget.attrs['placeholder'] = 'Write the task here'

todo_list/views.py
from django.shortcuts import render, redirect
from . import models
from accounts.models import UserAccount
from datetime import datetime
from django.utils.safestring import mark_safe
# To authenticate login infomration
from django.contrib.auth.decorators import login_required
from .forms import CreateEventForm

# Create your views here.
@login_required(login_url = 'accounts:login')
def index(request):
# get the account holder of the current login
       user = request.user
# get today's day from datetime object
       today = datetime.today()
# based on today's value fetch the whole data from calendar table
       dates_in_month = models.Calendar.objects.filter(month=today.month,
                     year=today.year).order_by('day').values_list('week_day', 'slug')
# Instantiate empty lists to hold calendar objects of the whole month
       calendar_obj = []
       week_days = [0, 1, 2, 3, 4, 5, 6] #["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
       months = ['January', 'February', 'March', 'April','May','June','July','August','September','October','November','December']
# loop through values_in_month and append calendar objects to calendar_obj
       for a_date in dates_in_month:
              calendar_obj.append(models.Calendar.objects.get(slug=a_date[1]))
# get context dictionary objects
       context = {
              'user': user,
              'calendar_obj': calendar_obj,
              'week_days': week_days,
              'calendar_month': months[today.month - 1],
              'calendar_year': today.year,
              'today': str(today).split(" ")[0],
              'today_day': today.day,
              'current_month': True,
              'slug': calendar_obj[1].slug
       }
       return render(request, 'todo_list/index.html', context=context)
##############################################################################################
# 
@login_required(login_url = 'accounts:login')
def todo_list(request, slug):
# get the user object
       user_obj = request.user
# get calendar object with the slug value
       calendar_obj = models.Calendar.objects.get(slug=slug)
# get an event object associated with this user and this calendar object
       event_obj = models.Events.objects.filter(user=user_obj, calendar=calendar_obj).order_by("event_scheduled_to_begin")
# Prepare the context needed for the page
       context = {
              'slug': slug,
              'user': user_obj,
              'events': event_obj,
       }
       return render(request, 'todo_list/todo_list.html', context=context)
################################################################################
#############    CREATE NEW EVENT  #############################################
@login_required(login_url="accounts:login")
def create_event(request, slug):
# get user object
       user_obj = request.user
# get calendar object through slug values
       calendar_obj = models.Calendar.objects.get(slug=slug)
       if request.method == 'POST':
              forms = CreateEventForm(request.POST)
# fetch form values from html form
              if forms.is_valid():
                     title_input = forms.cleaned_data['event_title']
                     event_description = forms.cleaned_data['event_description']
                     event_starts = request.POST.get('starts')
                     event_ends = request.POST.get('ends')
# create event object
                     events = models.Events.objects.create(
                            event_scheduled_to_begin = event_starts,
                            event_scheduled_to_end = event_ends,
                            event_description = event_description,
                            event_title = title_input,
                            calendar = calendar_obj,
                            user = user_obj,
                     )
# save event object
                     events.save()
# after saving redirect page to schedule_list
              return redirect('todo_list:todo_list', slug=slug)

       else:
              forms = CreateEventForm()
       context = {
              'forms': forms,
              'slug':slug,
              'user': user_obj,
       }
       return render(request, 'todo_list/create_event.html', context=context)
################################################################################
#############    UPDATE VIEWS ##################################################
@login_required(login_url='accounts:login')
def edit_events(request, id):
# get event object through its id
       event_obj = models.Events.objects.get(id=id)
 # get user profile object
       user_obj = request.user

       if request.method == 'POST':
# fetch form object with all its instances
              form = CreateEventForm(request.POST, instance=event_obj)
# validate this form object
              if form.is_valid():
# fetch and assign the newly inputted fields
                     event_obj.event_title = form.cleaned_data['event_title']
                     event_obj.event_description = form.cleaned_data['event_description']
                     event_obj.event_scheduled_to_begin = request.POST.get('starts')
                     event_obj.event_scheduled_to_end = request.POST.get('ends')
# save event object
                     event_obj.save()

                     return redirect('todo_list:todo_list', slug=event_obj.calendar.slug)
       else:
# renders the form in html when it's rendered before we press the submit button
              form = CreateEventForm(instance=event_obj)
       context = {
              'form': form,
              'event_obj': event_obj,
              'user': user_obj,
       }
       return render(request, 'todo_list/edit_events.html',context=context)
################################################################################
#############    DETAIL VIEWS ##################################################
@login_required(login_url='accounts:login')
def details_page(request, id):
# get event object through its id
       event_obj = models.Events.objects.get(id=id)
# get UserAccount objects
       user_obj = request.user
# retieve each fields of event object
# pack it in a dictionary
       if event_obj is not None:
              context = {
                     'event_obj': event_obj,
                     'user_obj': user_obj,
              }
       else:
              return redirect('todo_list:todo_list', slug=event_obj.calendar.slug)
# render the details page
       return render(request, 'todo_list/details_page.html', context=context)
################################################################################
#############    DELETE VIEWS ##################################################
@login_required(login_url='accounts:login')
def delete_events(request, id):
# get event object through event_id
       event_obj = models.Events.objects.get(id=id)
# get the list of event objects scheduled for the same day
       event_obj_list = models.Events.objects.filter(calendar=event_obj.calendar)
       if request.method == 'POST':
# delete event object
              event_obj.delete()
# If there are other events scheduled for the same day then go to schedule_list page
              if event_obj_list.count() != 0:
                     return redirect('todo_list:todo_list', slug=event_obj_list[0].calendar )
              else:
# otherwise go to calendar page
                     return redirect('todo_list:index')
       context = {
              'event_obj': event_obj,
       }
       return render(request, 'todo_list/delete.html', context=context )
################################################################################
#############    NEXT MONTH ####################################################

def next_month(request, slug):
# get the account holder of the current login
       user = request.user
# get the values of the current month and year from slug value
       calendar_obj = models.Calendar.objects.get(slug=slug)
# extract current month and year from calendar_obj
       current_month = calendar_obj.month
       current_year = calendar_obj.year
# we then calculate next_month and next_year
       next_month = current_month + 1
       next_year = current_year
       if next_month > 12:
              next_month = 1
              next_year = current_year + 1
              if next_year > 2025:
                     next_year = datetime.today().year
# we can get dates and other info about next_month from Calendar object
       dates_in_next_month = models.Calendar.objects.filter(month = next_month,
                                   year = next_year).order_by('day').values_list('id')
# populate calendar_obj with calendar objects of dates in next month
       next_calendar_month = []
       for obj in dates_in_next_month:
              next_calendar_month.append(models.Calendar.objects.get(id = obj[0]))
# create a context object for the calendar
       months = ['January', 'February', 'March', 'April','May','June','July','August','September','October','November','December']
       week_days = [0, 1, 2, 3, 4, 5, 6] # each number represents week days 0 for monday, 1 for tuesday, 2 for wednesday, 3 for thursday
       context = {
              'user':      user,
              'calendar_obj':      next_calendar_month,      # this is for the calendar dates
              'week_days' :        week_days,
              'calendar_month':    months[next_month-1],  # To display the month of the calendar
              'calendar_year':     next_year,    # to know when the year for the next month
              'slug':              next_calendar_month[0].slug,             # for the arrows to get the slug value
              'today':             str(datetime.today()).split(" ")[0],
       }#month_first_day

       if context['slug'] == context['today']:
              print("good it works")
       return render(request, 'todo_list/index.html', context=context)

templates/todo_list/delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="section-content padding-y">
       <div class="sign_up_container card mx-auto" style="max-width:620px; margin-top: 80px;">
              <article class="card-body">
                     <header class="mb-4">
                            <h4 class="card-title">Are You Sure You want To Delete This Task?</h4>
                     </header>
                     <form action="{% url 'todo_list:delete_event' event_obj.id %}" method='POST'>
                            {% csrf_token %}
                            <div class="form-row btn_row">
                                   {% comment %} <div class="form-group"> {% endcomment %}
                                          <div class="form-group">
                                                 <button type="submit" class="btn btn-primary btn-block" style="max-width:300px;">Delete</button>
                                          </div>
                                          <div class="form-group">
                                                 <a href="{% url 'todo_list:index' %}" class="btn btn-primary btn-block" style="max-width:300px;">Cancel</a>
                                          </div>
                                   {% comment %} </div> {% endcomment %}
                            </div>
                     </form>
              </article>
       </div>
</section>

{% endblock %}

templates/todo_list/details_page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="canvas">
       <div class="header">
              <nav class="header__nav">
                     <div class="header__left-content">
                            {% if user.profile_pic %}
                            <img src="{{ user.profile_pic.url }}" class="header__icon"
                                   style="max-width:120px; max-height:120px;"></img>
                            {% else %}
                                   <img src="{% static 'svg/user-solid.svg' %}" alt="" 
                                          style="max-width:150px; max-height:150px"></img>
                            {% endif %}
                     </div>
                     <div class="header__center">
                            <h2>{{ event_obj.event_title }}</h2>
                     </div>
                     <div class="header__right-content">
                            <ul class="header__list">
                                   <li>
                                          <a href="{% url 'accounts:my_profile' %}"> {{ user.username }} </a>
                                   </li>
                                   <li>
                                          <a href="{% url 'todo_list:index' %}"> To Calendar </a>
                                   </li>
                                   <li>
                                          <a href="{% url 'accounts:logout' %}"> Logout </a>
                                   </li>
                            </ul>
                     </div>
              </nav>
       </div>
       <div class="container_details">
              <div class="details">
                     <div class="one_block">
                            <p class="title_">planned action: &nbsp &nbsp {{ event_obj.event_title }}</p>
                     </div>
                     <div class="one_block">
                            <p class="title_">
                                   Event begins @: &nbsp &nbsp {{ event_obj.event_scheduled_to_begin }} 
                            </p>
                            <p class="title_">
                                   and ends @: &nbsp &nbsp {{ event_obj.event_scheduled_to_end }}       
                            </p>
                     </div>
                     <div class="one_block">
                            <p class="title_">
                                   planned action is: &nbsp &nbsp {{ event_obj.event_description }}
                            </p>
                     </div>
              </div>
              <div class="details_footer">
                     <ul class="footer__list">
                            <li>
                                   <a href="{% url 'todo_list:delete_event' event_obj.id %}" class="delete_btn">
                                          Delete
                                   </a>
                            </li>
                            <li>
                                   <a href="{% url 'todo_list:edit_event' event_obj.id %}" class="delete_btn">
                                          Edit
                                   </a>
                            </li>
                            <li>
                                   <a href="{% url 'todo_list:todo_list' event_obj.calendar.slug %}" class="delete_btn">
                                          To Schedule List
                                   </a>
                            </li>
                            <li>
                                   <a href="{% url 'todo_list:index' %}" class="delete_btn">
                                          To Calendar
                                   </a>
                            </li>
                     </ul>
              </div>
       </div>
</div>
{% endblock %}

templates/todo_list/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="canvas">
    <header class="header">
        <nav class="header__nav">
            <div class="header__left-content">
                {% if user.profile_pic %}
                <img src="{{ user.profile_pic.url }}" class="header__icon"
                     style="max-width:120px; max-height:120px;">
                {% else %}
                <img src="{% static 'svg/user-solid.svg' %}" class="header__icon"
                     style="max-width:70px; max-height:70px">
                {% endif %}
            </div>
            <div class="header__right-content">
                <ul class="header__list">
                    <li>
                        <a href="{% url 'accounts:my_profile' %}"> {{ user.username }} </a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:logout' %}"> Logout </a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="cal__main">
        <h1>calendar</h1>
        <div class="cal__container">

            <div class="calendar__top">
                <span class="arrow" id="back__arrow">
                    <a href="{% url 'todo_list:prev_month' slug %}">
                        {% comment %} <img src="{% static 'svg/chevron-left-square.svg' %}"
                            style="max-width:120px; max-height:120px;"> {% endcomment %}
                        <
                    </a>
                </span>
                {% if current_month %}
                <div class="calendar__day">
                    <span class="cal__month" id="cal__month">{{ calendar_month }} {{ today_day }}, {{ calendar_year }}</span>
                </div>
                {% else %}
                <div class="calendar__day">
                    <span class="cal__month" id="cal__month">{{ calendar_month }}, {{ calendar_year }}</span>
                </div>
                {% endif %}
                <div class="calendar__time">
                    <span class="cal__time" id="cal__time"></span>
                </div>
                <span class="arrow" id="forward__arrow">
                    <a href="{% url 'todo_list:next_month' slug %}">
                        {% comment %} <img src="{% static 'svg/chevron-right-square.svg' %}"
                            style="max-width:120px; max-height:120px;"> {% endcomment %}
                        >
                    </a>
                </span>
            </div>
            <div>
            </div>
            <div class="calendar__bottom">
                <div class="calendar__weekdays" id="cal__weekdays">
                    <span>Mon</span>
                    <span>Tue</span>
                    <span>Wed</span>
                    <span>Thu</span>
                    <span>Fri</span>
                    <span>Sat</span>
                    <span>Sun</span>
                </div>
                <div class="calendar__days" id="cal__days">
                    {% for calendar in calendar_obj %}
                    {% if calendar.day == 1 %}
                    {% for i in week_days %}
                    {% if i == calendar.week_day %}
                    {% if calendar.slug == today %}
                    <span class="today">
                        <a href="{{ calendar.get_url }}">
                            {{ calendar.day }}
                        </a>
                    </span>
                    {% else %}
                    <span>
                        <a href="{{ calendar.get_url }}">
                            {{ calendar.day }}
                        </a>
                    </span>
                    {% endif %}
                    {% elif i < calendar.week_day %}
                    <span></span>
                    {% else %}

                    {% endif %}
                    {% endfor %}

                    {% else %}
                    {% if calendar.slug == today %}
                    <span class="today">
                        <a href="{{ calendar.get_url }}">
                            {{ calendar.day }}
                        </a>
                    </span>
                    {% else %}
                    <span>
                        <a href="{{ calendar.get_url }}">
                            {{ calendar.day }}
                        </a>
                    </span>
                    {% endif %}
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
<div id="calendar"></div>
<div class="user__logout">
</div>

{% endblock %}

templates/todo_list/todo_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="canvas">
       <div class="header">
              <nav class="header__nav">
                     <div class="header__left-content">
                            {% if user.profile_pic %}
                                   <img src="{{ user.profile_pic.url }}" class="header__icon"
                                          style="max-width:120px; max-height:120px;"></img>
                            {% else %}
                                   <img src="{% static 'svg/user-solid.svg' %}" alt="" 
                                          style="max-width:150px; max-height:150px"></img>
                            {% endif %}
                     </div>
                     <div class="header__center">
                            <h2>Schedules of the day {{ slug }}</h2>
                     </div>
                     <div class="header__right-content">
                            <ul class="header__list">
                                   <li>
                                          <a href="{% url 'accounts:my_profile' %}"> {{ user.username }} </a>
                                   </li>
                                   <li>
                                          <a href="{% url 'todo_list:index' %}"> To Calendar </a>
                                   </li>
                                   <li>
                                          <a href="{% url 'accounts:logout' %}"> Logout </a>
                                   </li>
                            </ul>
                     </div>
              </nav>
       </div>
       <div class="container_todo_list">
              {% if events %}
                     {% for each_event in events %}
                     <div class="box">
                            <p class="hour">
                                   {{ each_event.event_scheduled_to_begin }} - {{ each_event.event_scheduled_to_end }}
                            </p>
                            <p class="title">
                                   <a href="{% url 'todo_list:details' each_event.id %}">
                                          {{ each_event.event_title }}
                                   </a>
                            </p>
                            <p>
                                   <a href="{% url 'todo_list:edit_event' each_event.id %}">
                                          <span class="edit">
                                                 <i class="fas fa-edit"> </i>
                                          </span>
                                   </a>
                            </p>
                     </div>
                     {% endfor %}
              {% else %}
              <div class="box">
                     <h2 class="title">
                            No event is planned for the day
                     </h2>
              </div>
              {% endif %}
              <div class="box">
                     <p class="hour">
                            <i class="fa fa-plus"></i>
                     </p>
                     <a href="{% url 'todo_list:create_event' slug %}" class="title">
                            New Schedule
                     </a>
              </div>
       </div>
</div>
{% endblock %}